### ISSUE TITLE
New Requirement From Format Review Team

### ISSUE THREAD

**Issue by duguyiqiu** [shumway/asudis#9]
Hi Prof. Shumway,

I am an ASU graduate student in EE and I used your template to format my Master's thesis. It helped me a lot and simplified my preparation. I appreciate that you have shared this online. 

Unfortunately the Format Review Team said my theis didn't pass the review because they require uppercase for chapter titles in tables of contents and title case for captions in list of figures. This is a new requirement that's updated in 2014.

I tried to research online to figure out how to use the tocloft package to do that but I it didn't get me anywhere. I was wondering if you could take a look at this and help me out?

Thank you very much!
Yiqiu Liu
Master of Science student,
School of Electrical, Computer and Energy Engineering,
Arizona State University

**Comment by shumway** [comment]
Hi Yiqui,

I left ASU in 2013. I can still help you, but please try one of these first:

* Post your question to the discussion group https://groups.google.com/forum/#!forum/asudis
or
* Look at Robert Kutter's (better!) dissertation package: https://github.com/GarenSidonius/ASU-Dissertation-Template

If you want to work with me to try to patch this formatting problem, please give a specific example of what is needed. Since I'm no longer at ASU, I'm not familiar with the 2014 style changes. Generally it's best if graduate students submit such corrections to this package themselves or toe Robert Kutter's newer package.

Thanks,
John

> On Oct 15, 2015, at 6:48 PM, Yiqiu Liu <notifications@github.com> wrote:
> 
> Hi Prof. Shumway,
> 
> I am an ASU graduate student in EE and I used your template to format my Master's thesis. It helped me a lot and simplified my preparation. I appreciate that you have shared this online.
> 
> Unfortunately the Format Review Team said my theis didn't pass the review because they require uppercase for chapter titles in tables of contents and title case for captions in list of figures. This is a new requirement that's updated in 2014.
> 
> I tried to research online to figure out how to use the tocloft package to do that but I it didn't get me anywhere. I was wondering if you could take a look at this and help me out?
> 
> Thank you very much!
> Yiqiu Liu
> Master of Science student,
> School of Electrical, Computer and Energy Engineering,
> Arizona State University
> 
> —
> Reply to this email directly or view it on GitHub.
> 

------
John Shumway, Ph. D.
Software Engineering Manager, Stone Ridge Technology
Adjunct Professor, Department of Physics, Arizona State University
http://jshumway.org, john.shumwayjr@gmail.com
http:://www.linkedin.com/in/johnshumway

**Comment by qmou** [comment]
The \@chapter command needs to be patched such that the chapter titles in TOC are all Capitalized. The following fix works for me:
```
\def\@chapter[#1]#2{\ifnum \c@secnumdepth >\m@ne
                        \refstepcounter{chapter}%
                        \typeout{\@chapapp\space\thechapter.}%
                        \addcontentsline{toc}{chapter}%
                        {\protect\numberline{\thechapter}\MakeUppercase{#1}}%
                    \else
                        \addcontentsline{toc}{chapter}{\MakeUppercase{#1}}%
                    \fi
                    \chaptermark{#1}%
```
